services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: sheet2schema_backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  frontend:
    build: 
      context: ./frontend
      target: dev
    container_name: sheet2schema_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api
    depends_on:
      - backend
    command: npm run dev
